skip_tags: true

environment:
  nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-b$env:APPVEYOR_BUILD_NUMBER"
  - npm --no-git-tag-version version %APPVEYOR_BUILD_VERSION%

build_script:
  - npm run build

build: on

test_script:
  - npm run test

test: on

artifacts:
  - path: build/bundle.user.js
    name: bundle.user.js

deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: Version $(appveyor_build_version)
  description: 'Changelog:'
  auth_token:
    secure: xMcnocRvXpoVccUdQMgu52bjunzTLDzCnxaeum8+74zTMxmRW7+iHD653YEd70VR
  repository: thorio/kgrabber
  artifact: bundle.user.js
  draft: true
  on:
    branch: master
